In [ ]:
import numpy as np #np is alias name, import is a keyword by using it we are importing numpy



In [ ]:
a = np.array([1,3,9,2])  # agar array me int ke saath ek string add kr de toh woh sabko string me convert kr dega, array ek hi datatypes ko store krta h
print (a)


[1 3 9 2]


In [ ]:
np_arr = np.array([3,3,3,3,3,3,'hello',False]) # numpy array ko vectors bhi bolte h
print(bool(np_arr[-1]))


a = False
print(bool(a))

True
False


In [ ]:
a =0
print(bool(a))

a ='0'
print(bool(a))

False
True


In [ ]:
a = np.zeros(5)  # iss bracket ke anar jitni value likhoge ye utni zero create kr dega
print(a)

[0. 0. 0. 0. 0.]


In [ ]:
a = np.zeros((2,3))
print(a)

[[0. 0. 0.]
 [0. 0. 0.]]


In [ ]:
a = np.zeros((2,3,4))
print(a)
print(type(a[0][0][0]))

[[[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]]
<class 'numpy.float64'>


In [ ]:
a = np.zeros((2,3,4), dtype =int) #dtype float ko int me convert kr deta h
print(a)
print(type(a[0][0][0]))

[[[0 0 0 0]
  [0 0 0 0]
  [0 0 0 0]]

 [[0 0 0 0]
  [0 0 0 0]
  [0 0 0 0]]]
<class 'numpy.int64'>


In [ ]:
a = np.ones((2,3,4))
print(a)
print(type(a[0][0][0]))

[[[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]

 [[1. 1. 1. 1.]
  [1. 1. 1. 1.]
  [1. 1. 1. 1.]]]
<class 'numpy.float64'>


In [ ]:

a = np.zeros((2,3,4,5))    #jitni chaho parameters likh sakte ho
print(a)

[[[[0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]]

  [[0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]]

  [[0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]]]


 [[[0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]]

  [[0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]]

  [[0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]
   [0. 0. 0. 0. 0.]]]]


In [ ]:
a = np.empty(4, dtype = int) # ye random value thata h from memory , garbage value
print(a)

[1 3 9 2]


In [ ]:
a = np.full(4,5, dtype = int) # four times 5 dega ye
print(a)

[5 5 5 5]


In [ ]:
a = np.arange(2,7, dtype = int) # ye 2 se print krna start karega and 6 tk print karega
print(a)

[2 3 4 5 6]


In [ ]:
a = np.arange(7) # ye 0 se print krna start karega and 6 tk print karega
print(a)

[0 1 2 3 4 5 6]


In [ ]:
a = np.arange(2,13, 4) # ye 2 se print krna start karega and 4 ke gap lekar for print karega , ye float me h int me convert krne ke liye dtype ka use hoga
print(a)

[ 2  6 10]


In [ ]:
a = np.linspace(3,12,4, dtype = int)
print(a)

[ 3  6  9 12]


In [ ]:
a = np.array([[1,2,3],[3,4,5]]) # this gives number of row and column
print(a.shape)

(2, 3)


In [ ]:
a = np.array([[1,2,3],[3,4,5]]) # this gives the total number of elements, or this gives the multiplication of both the values of shape
print(a.size)

6


In [ ]:
a = np.random.randint(1,7,4)
print(a)

[5 6 4 3]


In [ ]:
a = np.random.choice([2,4,2,9],2)
print(a)


[9 2]


In [ ]:
a = np.random.choice(7,size=(2,3)) #ye 2 ek matrix create karega jisme do row honge and and 3 column hogi and uske andar ki saari values 7 se km hogi
print(a)

[[0 3 4]
 [4 6 0]]


In [ ]:
a = np.array([1,2,3,4])
b= np.array([5,6,7,8])

print(a+b)
print(a * 2 *b)
print(a/b)

[ 6  8 10 12]
[10 24 42 64]
[0.2        0.33333333 0.42857143 0.5       ]


In [ ]:
#broadcasting , means saare elemnt pe koi scalar operation perform krna

a = np.array([1,2,3])
b= np.array([5,6,7,8])

print(a+b)   # it will givw value error
print(a * b) # value error


ValueError: operands could not be broadcast together with shapes (3,) (4,) 

In [ ]:
a = [1,2,3,4] # it will print two times in a single box
print(2 * a)

[1, 2, 3, 4, 1, 2, 3, 4]


In [ ]:
a = [1,2,3]  # it concat both the list
b = [4,5,6]

print(a + b)

[1, 2, 3, 4, 5, 6]


In [ ]:
a = np.random.randint()

In [ ]:
b = np.array([[1,2,3],[4,5,6]])   # ye corresponding elemnt ko lekar ek naya vector bna deta h jisme har ek array me 2 elements hote h
a = np.transpose(b)
print(a)

[[1 4]
 [2 5]
 [3 6]]


In [ ]:
a = np.random.randint(1,10, (2,3))
print(a)
b = np.random.randint(2,11, (2,3))
print(b)
c= np.concatenate((a,b))
print(c)

[[6 5 8]
 [1 1 7]]
[[ 7  9 10]
 [ 4  8 10]]
[[ 6  5  8]
 [ 1  1  7]
 [ 7  9 10]
 [ 4  8 10]]


In [ ]:
a = np.random.randint(1,10,5)
print(a)

b = np.random.randint(1,10,5)
print(b)

c= np.where(b>2,b,a) # first parameter is condition , if condition fulfills then we will take elemnt of b else we will take from a
print(c)

[6 3 4 1 3]
[4 2 3 2 8]
[4 3 3 1 8]


In [ ]:
a = np.random.randint(1,10,5)
print(a)

b = np.sort(a)
print(b)

[5 4 9 4 8]
[4 4 5 8 9]


In [ ]:
a = np.random.randint(1,10,5)
print(a)

b = np.sum(a)
print(b)

[2 8 5 2 4]
21


In [ ]:
a = np.random.randint(1,10,5)
b = np.random.randint(1,10,5)
print(a)
print(b)

c = np.add(a,b)
print(c)

[7 9 2 5 8]
[6 8 4 9 7]
[13 17  6 14 15]


In [ ]:
a = np.random.randint(1,10,5)
print(a)

b = np.mean(a)
print(b)

[8 5 3 1 1]
3.6


In [ ]:
a = np.random.randint(1,10,5)
print(a)

b = np.std(a)
print(b)

[2 2 7 7 5]
2.244994432064365


In [ ]:
a = np.random.randint(1,10,5)
print(a)

b = np.min(a)
print(b)

[2 1 5 9 1]
1


In [ ]:
a = np.random.randint(1,10,5)
print(a)

b = np.max(a)
print(b)

[8 5 2 7 5]
8


In [ ]:
a = np.random.randint(1,10,5)
print(a)

b = np.unique(a)
print(b)

[2 7 7 4 3]
[2 3 4 7]


In [ ]:
a = np.random.randint(1,10,5)
b= np.random.randint(2, 12, 5)
print(a)
print(b)

c= np.matmul(a,b)
print(b)

[8 8 2 2 3]
[ 3 10  6  7 11]
[ 3 10  6  7 11]


In [105]:

# scores = []

# days = ['monday','tesday','wed','thursday','friday','sat','sun']
# for i in range (7):
#   x = input(f'give the input for the {days[i]}')


scores = input().split()
print(scores)
scores = [int(i) for i in scores]

print(scores)

a = np.sum(scores)
b = np.mean(scores)
c = np.std(scores)
d = np.min(scores)
e = np.max(scores)
f = np.unique(scores)

print("Total :", a)
print("Mean :",b)
print("Standard Deviation :",c)
print("Minimum :",d)
print("Maximum :",e)
print("Unique :",f)

give the input for the monday120
give the input for the tesday341
give the input for the wed87
give the input for the thursday200
give the input for the friday120
give the input for the sat45
give the input for the sun34
[]


/usr/local/lib/python3.12/dist-packages/numpy/_core/fromnumeric.py:3596: RuntimeWarning: Mean of empty slice.
  return _methods._mean(a, axis=axis, dtype=dtype,
/usr/local/lib/python3.12/dist-packages/numpy/_core/_methods.py:138: RuntimeWarning: invalid value encountered in scalar divide
  ret = ret.dtype.type(ret / rcount)
/usr/local/lib/python3.12/dist-packages/numpy/_core/_methods.py:218: RuntimeWarning: Degrees of freedom <= 0 for slice
  ret = _var(a, axis=axis, dtype=dtype, out=out, ddof=ddof,
/usr/local/lib/python3.12/dist-packages/numpy/_core/_methods.py:175: RuntimeWarning: invalid value encountered in divide
  arrmean = um.true_divide(arrmean, div, out=arrmean,
/usr/local/lib/python3.12/dist-packages/numpy/_core/_methods.py:210: RuntimeWarning: invalid value encountered in scalar divide
  ret = ret.dtype.type(ret / rcount)


ValueError: zero-size array to reduction operation minimum which has no identity

In [106]:
a = np.array([3,3,3,3])

b =a
b[0] =1
print(a,b)

[1 3 3 3] [1 3 3 3]
