In [4]:
import numpy as np

In [31]:
#question 1

#create a 5x5 matrix of random integer(1-90)
a = np.random.randint(1,91, (5,5))
print(a,'\n');

#find mean of values row and column wise
row_wise_mean = np.mean(a, axis = 1)
print(b)

b = np.mean(a, axis = 0)
print(b, '\n')



#replace all even number with -1
c= np.where(a%2==0,-1,a)
print(c, '\n');


#sort the array row and column wise
sort_row = np.sort(a, axis = 1)
print(sort_row)

sort_col = np.sort(a, axis = 0)
print(sort_col, '\n')


# Find row and column wise sum separately
sum_row = np.sum(a, axis = 1)
print(sum_row)

sum_col = np.sum(a, axis = 0)
print(sum_col, '\n')


# count the number of -ve in each column
count_col = np.sum(np.where(c<0, 1, 0), axis = 0)
print(count_col, '\n')


[[50 66 86 30 89]
 [ 6 30 49 88 37]
 [47 10 45 28 77]
 [34 52 82  8  1]
 [65 60 79 46 64]] 

[31.8 45.2 55.  24.  42.4]
[40.4 43.6 68.2 40.  53.6] 

[[-1 -1 -1 -1 89]
 [-1 -1 49 -1 37]
 [47 -1 45 -1 77]
 [-1 -1 -1 -1  1]
 [65 -1 79 -1 -1]] 

[[30 50 66 86 89]
 [ 6 30 37 49 88]
 [10 28 45 47 77]
 [ 1  8 34 52 82]
 [46 60 64 65 79]]
[[ 6 10 45  8  1]
 [34 30 49 28 37]
 [47 52 79 30 64]
 [50 60 82 46 77]
 [65 66 86 88 89]] 

[321 210 207 177 314]
[202 218 341 200 268] 

[3 5 2 5 1] 



In [48]:
#question 2

#create a 5x5 array(stock level)
stock = np.random.randint(20,80, (5,5))
print( "Available stock : ")
print(stock, '\n')


#create another 5x5 array(demand)

demand = np.random.randint(20,80,(5,5))
print("Demand :")
print(demand, '\n')

#compute : Remaining stock = stock- demand

remain_stock = stock - demand
print("remained_stock :")
print(remain_stock, '\n')


#Replace : Negative value ->0 (out of zero)

replace = np.where(remain_stock<0,0,remain_stock)
print("Negative Replaced with zero:")
print(replace, '\n')


#Find : Total Shortage

total_shortage = np.sum(np.where(remain_stock<0, remain_stock * -1, 0 ))
print("Total Shortage :")
print(total_shortage, '\n')

#products with zero stock

product_with_zero_stock = np.sum(np.sum(np.where(replace ==0, 1, 0) ,axis = 0))
print("product_with_zero_stock :")
print(product_with_zero_stock, '\n')


#sort row based on remaining

sorted = np.sort(replace, axis = 1)
print("sorted :")
print(sorted, '\n')





Available stock : 
[[74 30 52 62 65]
 [77 65 37 33 25]
 [40 43 24 75 52]
 [45 66 40 29 44]
 [59 21 77 41 29]] 

Demand :
[[75 42 74 72 60]
 [32 79 50 47 38]
 [55 25 44 58 23]
 [26 70 62 49 23]
 [63 57 72 41 50]] 

remained_stock :
[[ -1 -12 -22 -10   5]
 [ 45 -14 -13 -14 -13]
 [-15  18 -20  17  29]
 [ 19  -4 -22 -20  21]
 [ -4 -36   5   0 -21]] 

Negative Replaced with zero:
[[ 0  0  0  0  5]
 [45  0  0  0  0]
 [ 0 18  0 17 29]
 [19  0  0  0 21]
 [ 0  0  5  0  0]] 

Total Shortage :
241 

product_with_zero_stock :
17 

sorted :
[[ 0  0  0  0  5]
 [ 0  0  0  0 45]
 [ 0  0 17 18 29]
 [ 0  0  0 19 21]
 [ 0  0  0  0  5]] 



In [57]:
#pandas introduction



import pandas as pd

#fileRead = pd.read_csv("student_data.csv")
fileRead = pd.read_csv("student_data.csv", sep = ',') #used to separater to format the file
# print(fileRead)

print(fileRead.head()) #bydefault 5 data print karega top se
#print(fileRead.head(6)) #need ke according arguement bhi de sakte h

#print(fileRead.tail()) # last se 5 data print karega
#print(fileRead.tail(7)) # arhument bhi de sakte h







   study_hours  attendance  sleep_hours  internet_usage  \
0            7          56            8               7   
1            4          69            5               3   
2           11          60            7               6   
3            8          99            9               8   
4            5          52            8               6   

   assignments_completed  previous_score  exam_score placement_status  
0                     10              62      100.00           Placed  
1                      8              56      100.00           Placed  
2                     10              45      100.00           Placed  
3                      4              55       90.17           Placed  
4                      8              40       78.82           Placed  
