<a href="https://colab.research.google.com/github/samarkumar4355/Data_Science/blob/main/Revision.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [7]:
a = np.arange(2,9)
print(a)
print(type(a[0]))

print(type(a))



[2 3 4 5 6 7 8]
<class 'numpy.int64'>
<class 'numpy.ndarray'>


In [10]:
a = np.arange(2,14, 4)
print(a)



[ 2  6 10]


In [12]:
a = np.arange(2,15, 4)
print(a)


[ 2  6 10 14]


In [17]:
a = np.linspace(3,12,4, dtype = int) # 3 se start karega and 12 tk jayega continuation me , 3rd argument ki jitni value hogi utni size ka array create hoga, agar need hui toh elemenbts repeat bhi hoga
print(a)

[ 3  6  9 12]


In [19]:
a = np.linspace(3,12,20, dtype = int)   # array sorted format me create krta h
print(a)

print(a.shape)   # this gives the size of the array

[ 3  3  3  4  4  5  5  6  6  7  7  8  8  9  9 10 10 11 11 12]
(20,)


In [24]:
a = np.random.randint(1,7,4)  # first argument -> from where to start, 2nd -> end -1, 3rd -> size of array
print(a)

a = np.random.randint(1,7,10)
print(a)

a = np.random.randint(1,7,(4,3))
print(a)


[6 1 4 4]
[1 2 1 3 5 1 3 1 1 6]
[[6 2 4]
 [6 1 4]
 [3 2 6]
 [5 2 3]]


In [29]:
a = np.random.choice([2,4,2,9],5)    # this will create an array of size 5, any elements randomly pick from given array to create new array of size 5
print(a)

a = np.random.choice([2,4,2,9],(4,5))
print(a)

[2 9 2 2 2]
[[9 2 9 9 2]
 [4 4 2 9 2]
 [2 9 4 9 4]
 [4 2 2 2 4]]


In [31]:
b = np.array([[1,2,3],[4,5,6], [7,8,9]])  # creates a new vecotr by taking corresponding elemnts of each vector.
a = np.transpose(b)
print(a)


[[1 4 7]
 [2 5 8]
 [3 6 9]]
